[package]
name = "heartbeats-sys"
version = "0.1.0"
authors = ["Connor Imes <cimes@mozilla.com>"]

[dependencies]
libc = "0.1"

[dependencies.energymon-sys]
git = "https://github.com/connorimes/energymon-sys.git"
