[package]
name = "heartbeats_sys"
version = "0.1.0"
authors = ["Connor Imes <cimes@mozilla.com>"]
build="build.rs"

[dependencies]
libc = "0.1"

[dependencies.energymon_sys]
git = "https://github.com/connorimes/energymon_sys.git"
